name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set current directory
      run: |
        pwd; ls; ls ..
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.8.0'
        ODFE_VERSION: '1.9.0.2'
        REPO: thisisqasim
      with:
        context: demo
        file: Dockerfile
        build-args: VERSION=${{ env.VERSION }},ODFE_VERSION=${{ env.ODFE_VERSION }}
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.REPO }}/elasticsearch:${{ env.VERSION }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
